In [9]:
import pandas as pd
import numpy as np
import json
import re

## Load Dataset

In [10]:
data = []

with open("../data/resumes_dataset.jsonl", "r", encoding="utf-8") as file:
    for line in file:
        data.append(json.loads(line))

df = pd.DataFrame(data)

print(df.shape)

(3500, 12)

## Check One Resume

In [11]:
print(df.loc[0, "Text"][:1000])

jessica claire montgomery street san francisco ca 94105 555 4321000 resumesampleexamplecom professional summary highly skilled software development professional bringing 10 years software design development integration advanced knowledge java skills agile html xml jdbc tomcat work history senior java developertech lead 2014 current synnex corporation tracy ca java developer agile scrum team javascript java develop customer facing internal web applications underlying component applications wrote maintainable extensible code team environment implemented designs including experimentation multiple iterations system administrator 102011 112013 mantech international corporation joint base mcguire nj technical lead system administrator oracle ebusiness suite erp application mentored technical staff java developerscada system admin 092008 102011 big lots anniston al developed maintained internal web applications managed scada system wind energy business business analyst 2008 092008 john deere

## Create Cleaning Function

In [12]:
def clean_resume(text):

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove Email
    text = re.sub(r"\S+@\S+", "", text)

    # Remove Phone Number
    text = re.sub(r"\+?\d[\d\s\-\(\)]{8,}", "", text)

    # Remove Special Characters
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # Remove Multiple Spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

## Apply Cleaning

In [14]:
# Apply Cleaning Function

df["Clean_Text"] = df["Text"].apply(lambda x: clean_resume(x))

print("Clean_Text column created successfully.")

df[["Text", "Clean_Text"]].head()

Clean_Text column created successfully.

,Text,Clean_Text
0,jessica claire montgomery street san francisco...,jessica claire montgomery street san francisco...
1,jared arthur maica java developer 17994568777 ...,jared arthur maica java developer linkedincomi...
2,jessica claire 9 resumesampleexamplecom 555 43...,jessica claire 9 resumesampleexamplecom montgo...
3,jessica claire 9 resumesampleexamplecom 555 43...,jessica claire 9 resumesampleexamplecom montgo...
4,jessica claire 100 montgomery st 10th floor xx...,jessica claire 100 montgomery st 10th floor xx...

## Compare Original vs Clean Text

In [15]:
print("="*80)
print("ORIGINAL TEXT\n")
print(df.loc[0, "Text"][:700])

print("\n" + "="*80)

print("CLEAN TEXT\n")
print(df.loc[0, "Clean_Text"][:700])

================================================================================
ORIGINAL TEXT

jessica claire montgomery street san francisco ca 94105 555 4321000 resumesampleexamplecom professional summary highly skilled software development professional bringing 10 years software design development integration advanced knowledge java skills agile html xml jdbc tomcat work history senior java developertech lead 2014 current synnex corporation tracy ca java developer agile scrum team javascript java develop customer facing internal web applications underlying component applications wrote maintainable extensible code team environment implemented designs including experimentation multiple iterations system administrator 102011 112013 mantech international corporation joint base mcguire

================================================================================
CLEAN TEXT

jessica claire montgomery street san francisco ca resumesampleexamplecom professional summary highly skilled software development professional bringing 10 years software design development integration advanced knowledge java skills agile html xml jdbc tomcat work history senior java developertech lead 2014 current synnex corporation tracy ca java developer agile scrum team javascript java develop customer facing internal web applications underlying component applications wrote maintainable extensible code team environment implemented designs including experimentation multiple iterations system administrator mantech international corporation joint base mcguire nj technical lead system adminis

## Text Length Comparison

In [16]:
df["Original_Length"] = df["Text"].apply(len)
df["Clean_Length"] = df["Clean_Text"].apply(len)

df[["Original_Length", "Clean_Length"]].head()

   Original_Length  Clean_Length
0             1589          1495
1             1727          1686
2             5608          5555
3            12888         12834
4             4237          4181

## Check if Any Empty Resume Exists

In [17]:
print("Empty Clean Resumes :", (df["Clean_Text"].str.strip() == "").sum())

Empty Clean Resumes : 0

## Check Duplicate Resumes After Cleaning

In [18]:
duplicates = df["Clean_Text"].duplicated().sum()

print("Duplicate Clean Resumes :", duplicates)

Duplicate Clean Resumes : 197

## Select Important Columns

In [19]:
final_df = df[
    [
        "ResumeID",
        "Category",
        "Skills",
        "Education",
        "Experience",
        "Clean_Text",
        "Text",
        "Source"
    ]
]

final_df.head()

,ResumeID,Category,Skills,Education,Experience,Clean_Text,Text,Source
0,REAL_0001,Java Developer,"Python, SQL, Git, Linux",Computer Science degree,jessica claire montgomery street san francisco...,jessica claire montgomery street san francisco...,jessica claire montgomery street san francisco...,ResumeAtlas
1,REAL_0002,Java Developer,"Python, SQL, Git, Linux",Computer Science degree,jared arthur maica java developer 17994568777 ...,jared arthur maica java developer linkedincomi...,jared arthur maica java developer 17994568777 ...,ResumeAtlas
2,REAL_0003,Java Developer,"Python, SQL, Git, Linux",Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,jessica claire 9 resumesampleexamplecom montgo...,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas
3,REAL_0004,Java Developer,"Python, SQL, Git, Linux",Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,jessica claire 9 resumesampleexamplecom montgo...,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas
4,REAL_0005,Java Developer,"Python, SQL, Git, Linux",Computer Science degree,jessica claire 100 montgomery st 10th floor xx...,jessica claire 100 montgomery st 10th floor xx...,jessica claire 100 montgomery st 10th floor xx...,ResumeAtlas

## Final Dataset Information

In [20]:
print(final_df.shape)

final_df.info()

(3500, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ResumeID    3500 non-null   object
 1   Category    3500 non-null   object
 2   Skills      3500 non-null   object
 3   Education   3500 non-null   object
 4   Experience  3500 non-null   object
 5   Clean_Text  3500 non-null   object
 6   Text        3500 non-null   object
 7   Source      3500 non-null   object
dtypes: object(8)
memory usage: 218.9+ KB

## Save Clean Dataset

In [21]:
final_df.to_csv("../data/final_resume_dataset.csv", index=False)

print("Final Resume Dataset Saved Successfully")

Final Resume Dataset Saved Successfully

# Conclusion

✔ Raw resume text cleaned successfully.

✔ Created Clean_Text column.

✔ Removed URLs, emails, phone numbers and special characters.

✔ Selected important features for model training.

✔ Saved final dataset as final_resume_dataset.csv.